version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=feedget
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ../data:/var/lib/postgres
